
name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1.2
        with:
          input_dir: .
          output_dir: pdfs
          images_dir: img/
          # for example <img src="./images/file-name.png">
          image_import: ./images
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
